services:
  web:
    image: ${WEB_IMAGE_NAME}
    container_name: ${WEB_HOST}
    restart: always
    depends_on:
      - appointments-db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo18-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      HOST: ${DB_HOST}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
    command: odoo -d odoo_db --db_user=${DB_USER} --db_password=${DB_PASSWORD} --db_host=${DB_HOST}

  appointments-db:
    image: ${DB_IMAGE}
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data

volumes:
  odoo18-db-data:
  odoo18-web-data:
